### ISSUE TITLE
Modifier les arguments de coordinateShips

### ISSUE THREAD

**Issue by courentin** [alexballet/LO23-Battleship-Online#19]
Change this method :
https://github.com/alexballet/LO23-Battleship-Online/blob/af5ec7d820b3d51940ef060e020f0e25824b72ac/src/main/java/interfacesData/IDataTable.java#L47

To : 
```java
public void coordinateShips(List<Boat> listposition);
```
Data need boat type AND position. (`Position` is linked to `Boat`)

**Comment by LolaJC** [comment]
It is now : 
```public void coordinateShips(List<Boat> listBoat);```
