### ISSUE TITLE
NullPointerException dans NetworkModuleInterface.sendShot

### ISSUE THREAD

**Issue by courentin** [alexballet/LO23-Battleship-Online#37]
Lors de l'utilisation de NetworkModuleInterface.sendShot, j'ai un NullPointerException à cette ligne : 

https://github.com/alexballet/LO23-Battleship-Online/blob/588ee69884e561cf5f6301d1e02ab38eb0ab70c1/src/main/java/lo23/battleship/online/network/NetworkModuleInterface.java#L140 

Il semblerait que `game.getPlayer2()`soit null.

La fonction est appelé par Data ici : 
https://github.com/alexballet/LO23-Battleship-Online/blob/143dd73a28f15f366ce1ee89bd1425ebd0f7ba20/src/main/java/data/CDataTable.java#L56

**Comment by courentin** [comment]
Le pb se pose lorsque l'on fait une partie avec le robot

**Comment by LolaJC** [comment]
C'est normal ! Il n'y a rien d'où le pointeur null. Un Player robot a été ajouté dans la version 4

**Comment by courentin** [comment]
Génial :)
